# Generated by Django 4.2.7 on 2023-11-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
