# Generated by Django 4.2.7 on 2023-12-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_sale_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
