# Generated by Django 4.2.7 on 2024-01-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_subscription_profile_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='profile',
        ),
    ]
