# Generated by Django 4.2.7 on 2024-01-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_remove_profile_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_subscriptions', to='user.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard_monthly', 'Standard Monthly'), ('standard_yearly', 'Standard Yearly'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], default='free', max_length=20),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
