# Generated by Django 4.2.7 on 2024-01-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_customuser_subscription_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscriptions', to='user.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard_monthly', 'Standard Monthly'), ('standard_yearly', 'Standard Yearly'), ('premium_monthly', 'Premium Monthly'), ('premium_yearly', 'Premium Yearly')], default='free', max_length=20, unique=True),
        ),
    ]
