# Generated by Django 4.2.7 on 2024-01-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='contact_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
