# Generated by Django 4.2.7 on 2024-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total_quantity_sold',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
