# Generated by Django 4.2.7 on 2024-01-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_products_total_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='total_quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
