# .github/workflows/checks.yml
name: Checks

on: [push]

jobs:
  flake8:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8

      # - name: Set up test database
      #   run: |
      #     cp db.sqlite3 test_db.sqlite3

      - name: Run tests
        run: |
          python manage.py test
